#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DEATH_REPO == "DeathBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $DEATH_REPO == "Deathbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $DEATH_REPO =~ $regex ]]
    then
        if [[ $DEATH_REPO_BRANCH ]]
        then
            echo "${DEATH_REPO}/archive/${DEATH_REPO_BRANCH}.zip"
        else
            echo "${DEATH_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myDeathbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting DeathBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m hellbot
}

start_bot
